# List of definitions of analyses to be perfomed
# See config/README.md for more information 

analyses:
  - analysis: first-analysis
    samples: config/samples.tsv
    design: ~ condition
    results:
      contrasts:
          - ["condition", "all"]
    pca:
      pcs: [PC1, PC2]
      color_by: condition

